# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/android:api-30-ndk
  working_directory: ~/brd-mobile
  resource_class: medium+

  environment:
    SDK_FILENAME: sdk-tools-linux-4333796.zip
    ANDROID_HOME: /opt/android/sdk

version: 2.1

commands:
  # Default init command
  default-project-setup:
    steps:
      - checkout
      - pull-submodules
      - refresh-gradle

  # Pull submodules command
  pull-submodules:
    steps:
      # Pull submodules
      - run:
          name: Pull submodules
          command: |
            git submodule update --init --recursive

  # Refresh gradle command
  refresh-gradle:
    steps:
      # Restore cache - Gradle
      - restore_cache:
          name: Restoring cache - Gradle
          keys:
            - v1-dependencies-{{ checksum "brd-android/build.gradle.kts" }}-{{ checksum "brd-android/app/build.gradle.kts" }}

      # Refresh gradle
      - run:
          name: Refresh gradle
          command: |
            ./gradlew   dependencies

      # save cache - Gradle
      - save_cache:
          name: Saving cache - Gradle
          key: v1-dependencies-{{ checksum "brd-android/build.gradle.kts" }}-{{ checksum "brd-android/app/build.gradle.kts" }}
          paths:
            - ~/.gradle

jobs:
  # Test job (run tests & generate Jacoco report)
  test:
    <<: *defaults
    steps:
      # Setup project
      - default-project-setup

      # Unit tests
      - run:
          name: Run unit tests
          command: |
            ./gradlew  --console=plain  testDevelopmentTestnetDebugUnitTest

      # Generate Jacoco report
      - run:
          name: Generate Jacoco report
          command: |
            ./gradlew  --console=plain :brd-android:app:jacocoTestReport

  # Release job (build apk and aab)
  release:
    <<: *defaults
    steps:
      # Setup project
      - default-project-setup

      # Prepare keystore
      - run:
          name: Prepare keystore
          command: |
            mkdir /home/circleci/key
            echo $release_keystore > /home/circleci/key/base64
            base64 -d /home/circleci/key/base64 > /home/circleci/key/keystore
            ls -la /home/circleci/key

      # Build apk
      - run:
          name: Build release apk
          command: |
            ./gradlew --console=plain brd-android:app:assembleProductionMainnetRelease  -Pandroid.injected.signing.store.file='/home/circleci/key/keystore' -Pandroid.injected.signing.store.password=$release_password -Pandroid.injected.signing.key.alias='key0' -Pandroid.injected.signing.key.password=$release_sign_password

      # Build app bundles
      - run:
          name: Build release aab
          command: |
            ./gradlew --console=plain brd-android:app:bundleProductionMainnetRelease  -Pandroid.injected.signing.store.file='/home/circleci/key/keystore' -Pandroid.injected.signing.store.password=$release_password -Pandroid.injected.signing.key.alias='key0' -Pandroid.injected.signing.key.password=$release_sign_password

      # Prepare artifacts
      - run:
          name: Prepare artifacts
          command: |
            mkdir -p ~/atrifacts
            cp -r ./app/build/outputs/apk/productionMainnet/release ~/atrifacts;
            cp -r ./app/build/outputs/bundle/productionMainnetRelease ~/atrifacts;
          when: always

      # Upload artifacts
      - store_artifacts:
          path: ~/atrifacts
workflows:
  test_and_build:
    jobs:
      - test
      - release:
          filters:
            branches:
              only:
                - /release\/.*/
          requires:
            - test
